SELECT
    IMAGES.IMAGE_PATH,
    AVG(PHOTORATING.RATING) AS AVG_RATING
FROM 
    IMAGES
INNER JOIN photorating
ON
    IMAGES.IMAGE_ID = PHOTORATING.PHOTOID
WHERE
    IMAGES.CATEGORY_ID = 28
GROUP BY
    IMAGES.IMAGE_PATH
ORDER BY
    AVG_RATING DESC
